### ISSUE TITLE
How to make pitch accent correct on cards copied into Lapis?

### ISSUE THREAD

**Issue by Skretkowicz** [donkuri/lapis#70]
I wanted to copy my cards from Lapis deck into Kaishi but I noticed that after copying, all of the cards have 2-4 pitch accents at the same time, even when the word has only one pitch added:

<img width="1002" alt="Image" src="https://github.com/user-attachments/assets/df5adc8a-f18c-4558-8bbf-5baa8b2b6145" />

<img width="213" alt="Image" src="https://github.com/user-attachments/assets/05a910ca-c45e-4447-b819-3d6f1c224945" />

How to make pitch accent correct on cards copied into Lapis? 

how can I update the cards so that only one pitch position is shown?

**Comment by bewizible** [comment]
Oh, you're working on an update to fix this @itokatsu ?

**Comment by donkuri** [comment]
@itokatsu I don't remember, was this fixed in a recent PR or not?

**Comment by donkuri** [comment]
No worries!

**Comment by Skretkowicz** [comment]
Hello,
I just updated and this is still not fixed for me as of 1.5.1

**Comment by Skretkowicz** [comment]
Can you explain how to generate numerical pitch in AJT? I only see option to generate furigana and katakana. Thank you!
